# Generated by Django 5.2.6 on 2025-09-11 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('clinicas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilveterinario',
            name='clinica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinicas.clinica'),
        ),
        migrations.AddField(
            model_name='perfilveterinario',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
