# Generated by Django 5.2.6 on 2025-12-03 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilveterinario',
            name='duracion_turno_default',
            field=models.IntegerField(default=30, help_text='Duración en minutos'),
        ),
        migrations.AddField(
            model_name='perfilveterinario',
            name='firma_digital',
            field=models.ImageField(blank=True, null=True, upload_to='firmas/'),
        ),
        migrations.AddField(
            model_name='perfilveterinario',
            name='recibir_emails_reservas',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='perfilveterinario',
            name='telefono_profesional',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
