# Generated by Django 5.2.6 on 2025-09-11 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Clinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('direccion', models.TextField()),
                ('telefono', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('hora_apertura', models.TimeField()),
                ('hora_cierre', models.TimeField()),
                ('dias_atencion', models.JSONField(default=list, help_text="Lista de días: ['lunes', 'martes', ...]")),
                ('is_active', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(limit_choices_to={'role': 'admin_veterinaria'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Clínica',
                'verbose_name_plural': 'Clínicas',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='HorarioEspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('cerrado', models.BooleanField(default=False)),
                ('hora_apertura_especial', models.TimeField(blank=True, null=True)),
                ('hora_cierre_especial', models.TimeField(blank=True, null=True)),
                ('motivo', models.CharField(blank=True, max_length=200)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicas.clinica')),
            ],
            options={
                'verbose_name': 'Horario Especial',
                'verbose_name_plural': 'Horarios Especiales',
                'unique_together': {('clinica', 'fecha')},
            },
        ),
    ]
