# Generated by Django 5.2.6 on 2025-10-15 21:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinicas', '0001_initial'),
        ('mascotas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadoTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('codigo', models.CharField(choices=[('pendiente', 'Pendiente'), ('confirmado', 'Confirmado'), ('en_curso', 'En curso'), ('completado', 'Completado'), ('cancelado', 'Cancelado'), ('no_asistio', 'No asistió')], max_length=20, unique=True)),
                ('color', models.CharField(default='#6c757d', max_length=7)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='DisponibilidadVeterinario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('duracion_turno', models.PositiveIntegerField(default=30, help_text='Duración en minutos')),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicas.clinica')),
                ('veterinario', models.ForeignKey(limit_choices_to={'rol': 'veterinario'}, on_delete=django.db.models.deletion.CASCADE, related_name='disponibilidades', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Disponibilidad del Veterinario',
                'verbose_name_plural': 'Disponibilidades de Veterinarios',
                'ordering': ['fecha', 'hora_inicio'],
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField(blank=True, null=True)),
                ('duracion_minutos', models.PositiveIntegerField(default=30)),
                ('tipo_consulta', models.CharField(default='consulta', max_length=50)),
                ('motivo', models.TextField(blank=True)),
                ('reservado', models.BooleanField(default=False)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(blank=True, limit_choices_to={'rol': 'cliente'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='turnos_cliente', to=settings.AUTH_USER_MODEL)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clinicas.clinica')),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='turnos.estadoturno')),
                ('mascota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='mascotas.mascota')),
                ('veterinario', models.ForeignKey(limit_choices_to={'rol': 'veterinario'}, on_delete=django.db.models.deletion.CASCADE, related_name='turnos_vet', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['fecha', 'hora_inicio'],
                'unique_together': {('veterinario', 'fecha', 'hora_inicio')},
            },
        ),
    ]
