# Generated by Django 5.2.6 on 2025-10-16 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disponibilidadveterinario',
            name='fecha_fin',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='disponibilidadveterinario',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
    ]
