# Generated by Django 5.2.6 on 2025-10-16 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('turnos', '0002_disponibilidadveterinario_fecha_fin_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='disponibilidadveterinario',
            options={'ordering': ['-fecha_inicio', 'hora_inicio'], 'verbose_name': 'Disponibilidad del Veterinario', 'verbose_name_plural': 'Disponibilidades de Veterinarios'},
        ),
        migrations.RemoveField(
            model_name='disponibilidadveterinario',
            name='fecha',
        ),
    ]
