# Generated by Django 5.2.6 on 2025-10-05 23:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Especie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=50, unique=True)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("activo", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "Especie",
                "verbose_name_plural": "Especies",
                "ordering": ["nombre"],
            },
        ),
        migrations.CreateModel(
            name="Raza",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                ("descripcion", models.TextField(blank=True, null=True)),
                ("activo", models.BooleanField(default=True)),
                (
                    "especie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="razas",
                        to="mascotas.especie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Raza",
                "verbose_name_plural": "Razas",
                "ordering": ["especie", "nombre"],
                "unique_together": {("nombre", "especie")},
            },
        ),
        migrations.CreateModel(
            name="Mascota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "sexo",
                    models.CharField(
                        choices=[("M", "Macho"), ("H", "Hembra")], max_length=1
                    ),
                ),
                (
                    "fecha_nacimiento",
                    models.DateField(
                        blank=True,
                        help_text="Fecha aproximada de nacimiento",
                        null=True,
                    ),
                ),
                ("color", models.CharField(blank=True, max_length=100)),
                (
                    "peso",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Peso en kilogramos",
                        max_digits=6,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0.01)],
                    ),
                ),
                (
                    "numero_chip",
                    models.CharField(
                        blank=True,
                        help_text="Número de microchip",
                        max_length=50,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "foto",
                    models.ImageField(
                        blank=True, null=True, upload_to="mascotas/fotos/"
                    ),
                ),
                (
                    "esterilizado",
                    models.BooleanField(
                        default=False, help_text="¿Está castrado/esterilizado?"
                    ),
                ),
                (
                    "alergias",
                    models.TextField(
                        blank=True,
                        help_text="Alergias conocidas (medicamentos, alimentos, etc.)",
                    ),
                ),
                (
                    "condiciones_preexistentes",
                    models.TextField(
                        blank=True,
                        help_text="Condiciones médicas crónicas o importantes",
                    ),
                ),
                (
                    "observaciones",
                    models.TextField(
                        blank=True, help_text="Observaciones generales sobre la mascota"
                    ),
                ),
                (
                    "activo",
                    models.BooleanField(
                        default=True, help_text="Mascota activa en el sistema"
                    ),
                ),
                (
                    "fecha_fallecimiento",
                    models.DateField(
                        blank=True,
                        help_text="Fecha de fallecimiento (si aplica)",
                        null=True,
                    ),
                ),
                ("fecha_registro", models.DateTimeField(auto_now_add=True)),
                ("fecha_modificacion", models.DateTimeField(auto_now=True)),
                (
                    "dueno",
                    models.ForeignKey(
                        limit_choices_to={"rol": "cliente"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mascotas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "especie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="mascotas",
                        to="mascotas.especie",
                    ),
                ),
                (
                    "raza",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="mascotas",
                        to="mascotas.raza",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mascota",
                "verbose_name_plural": "Mascotas",
                "ordering": ["-fecha_registro"],
                "indexes": [
                    models.Index(
                        fields=["dueno", "activo"],
                        name="mascotas_ma_dueno_i_8b6b21_idx",
                    ),
                    models.Index(
                        fields=["numero_chip"], name="mascotas_ma_numero__01f3a0_idx"
                    ),
                ],
            },
        ),
    ]
