# Generated by Django 5.2.6 on 2025-11-30 23:13

import apps.historiales.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinicas', '0001_initial'),
        ('mascotas', '0001_initial'),
        ('turnos', '0003_alter_disponibilidadveterinario_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoriaClinica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now)),
                ('motivo_consulta', models.CharField(max_length=255)),
                ('peso_actual', models.DecimalField(decimal_places=2, help_text='Peso en KG', max_digits=5)),
                ('temperatura', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('frecuencia_cardiaca', models.IntegerField(blank=True, help_text='LPM', null=True)),
                ('anamnesis', models.TextField(help_text='Antecedentes y síntomas descritos')),
                ('hallazgos_fisicos', models.TextField(blank=True, help_text='Lo que el vet observa en el examen')),
                ('diagnostico', models.TextField()),
                ('tratamiento_realizado', models.TextField(help_text='Lo que se hizo EN la consulta')),
                ('indicaciones_dueno', models.TextField(help_text='Receta/Instrucciones para casa')),
                ('es_borrador', models.BooleanField(default=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('clinica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historias_clinicas', to='clinicas.clinica')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='historial_medico', to='mascotas.mascota')),
                ('turno', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historia_clinica', to='turnos.turno')),
                ('veterinario', models.ForeignKey(limit_choices_to={'rol': 'veterinario'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historia Clínica',
                'verbose_name_plural': 'Historias Clínicas',
                'ordering': ['-fecha'],
            },
        ),
        migrations.CreateModel(
            name='ArchivoAdjunto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to=apps.historiales.models.historia_clinica_upload_path)),
                ('descripcion', models.CharField(blank=True, help_text='Ej: Radiografía tórax', max_length=100)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('historia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='archivos', to='historiales.historiaclinica')),
            ],
            options={
                'verbose_name': 'Archivo Adjunto',
                'verbose_name_plural': 'Archivos Adjuntos',
            },
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Ej: Quintuple, Antirrábica', max_length=100)),
                ('lote', models.CharField(blank=True, help_text='Para trazabilidad en caso de problemas', max_length=50)),
                ('fecha_aplicacion', models.DateField(default=django.utils.timezone.now)),
                ('fecha_proxima_aplicacion', models.DateField(help_text='Fecha para el recordatorio automático')),
                ('historia_clinica', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacunas_aplicadas', to='historiales.historiaclinica')),
                ('mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacunas', to='mascotas.mascota')),
                ('veterinario', models.ForeignKey(limit_choices_to={'rol': 'veterinario'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Vacuna',
                'verbose_name_plural': 'Vacunas',
                'ordering': ['-fecha_aplicacion'],
            },
        ),
    ]
